// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedContainerIngress) DeepCopyInto(out *DedicatedContainerIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedContainerIngress.
func (in *DedicatedContainerIngress) DeepCopy() *DedicatedContainerIngress {
	if in == nil {
		return nil
	}
	out := new(DedicatedContainerIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedContainerIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedContainerIngressList) DeepCopyInto(out *DedicatedContainerIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DedicatedContainerIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedContainerIngressList.
func (in *DedicatedContainerIngressList) DeepCopy() *DedicatedContainerIngressList {
	if in == nil {
		return nil
	}
	out := new(DedicatedContainerIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedContainerIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedContainerIngressSpec) DeepCopyInto(out *DedicatedContainerIngressSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedContainerIngressSpec.
func (in *DedicatedContainerIngressSpec) DeepCopy() *DedicatedContainerIngressSpec {
	if in == nil {
		return nil
	}
	out := new(DedicatedContainerIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedContainerIngressStatus) DeepCopyInto(out *DedicatedContainerIngressStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedContainerIngressStatus.
func (in *DedicatedContainerIngressStatus) DeepCopy() *DedicatedContainerIngressStatus {
	if in == nil {
		return nil
	}
	out := new(DedicatedContainerIngressStatus)
	in.DeepCopyInto(out)
	return out
}
